### ISSUE TITLE
Question about spotify auth token

### ISSUE THREAD

**Issue by stavlocker** [DanielsWrath/SpotifyRandomizer#3]
Hi.
On my modified version of this I use an http server that runs on localhost which presents the spotify auth link to the user so he can copy it back to the program.

I've thought about making a PR with this, but then I got to wonder: How does this currently work? You state in the README.md that the redirect url should be `randomizer.py`.

So my main question is, how does this work without a web server? Does it work without a webserver? (If not, I'll submit my PR with the localhost web server)

**Comment by DanielHaitink** [comment]
If there isn't a web app available on the system, you have to copy the URL presented by the system and navigate to it on a different device with a browser available. Then you give the redirected URL to in the commandline. 

The redirect URL in the randomizer.py code is just the base URL and not the complete redirect URL that verifies your login.

If you are able to automate this, that would be great.

**Comment by stavlocker** [comment]
@DanielsWrath What I implemented isn't exactly automation, tell me what you think: When prompting for user auth, I start a web server that when the users authenticate looks something like this:
![image](https://user-images.githubusercontent.com/30472563/39255472-4c0c4f20-48b5-11e8-9d36-3adc0bed5f0a.png)
(And auto selects the text, I guess I could make it copy it to clipboard aswell) Which makes it nicer IMO. What do you think of this solution?

**Comment by stavlocker** [comment]
(bump)

**Comment by DanielHaitink** [comment]
Hey, sorry for the late response! Yes that seems like a good way of doing it! 😊
