### ISSUE TITLE
A link to SpotifyNoDupes?

### ISSUE THREAD

**Issue by stavlocker** [DanielsWrath/SpotifyRandomizer#6]
Hey 👋 I didn't know how to reach you since your website is down & your mail doesn't work, so I'm writing this here as I assume that by the time you read & delete this nobody else will :stuck_out_tongue_winking_eye:
Anyways I sent you this mail:

> Hey! It's me, the only one who contirubted to the SpotifyRandomizer repository besides you ;P
> Anyways, I just created a repository called [SpotifyNoDupes](https://github.com/stavlocker/spotifynodupes) and I linked SpotifyRandomizer (with a small thank you ;) I'd absolutely love it if you'd do the same. It's up to you though, so do whatever lol.
> 
>   \- Stav

You're more than welcome to delete this issue after you read it.

**Comment by DanielHaitink** [comment]
Sorry for the late response, I fixed my site so that works again 😄 I will add your repo to the README 👍
